version: '3'

services:
  redis:
    image: redis:7.0.4-alpine3.16
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass R23XdqSD3W1234E
    # environment:
      # - REDIS_PASSWORD=password123
    volumes: 
      - /redis-data:/var/lib/redis