version: '3'

services:
  amabotapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: amabot-docker
    container_name: amabotapp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      AMABOT_TELEGRAM_TOKEN: ${AMABOT_TELEGRAM_TOKEN}
      PORT: ${PORT}
      DB_HOST: amabot-db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
  db:
    image: postgres:14.3
    container_name: amabot-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
