// Generated by https://quicktype.io

export interface MercadoLibreResponse {
  site_id: string;
  country_default_time_zone: string;
  query: string;
  paging: Paging;
  results: Result[];
  sort: Sort;
  available_sorts: Sort[];
  filters: any[];
  available_filters: AvailableFilter[];
}

export interface AvailableFilter {
  id: string;
  name: string;
  type: string;
  values: AvailableFilterValue[];
}

export interface AvailableFilterValue {
  id: string;
  name: string;
  results: number;
}

export interface Sort {
  id: string;
  name: string;
}

export interface Paging {
  total: number;
  primary_results: number;
  offset: number;
  limit: number;
}

export interface Result {
  id: string;
  site_id: string;
  title: string;
  seller: Seller;
  price: number;
  prices: Prices;
  sale_price: null;
  currency_id: string;
  available_quantity: number;
  sold_quantity: number;
  buying_mode: string;
  listing_type_id: string;
  stop_time: string;
  condition: string;
  permalink: string;
  thumbnail: string;
  thumbnail_id: string;
  accepts_mercadopago: boolean;
  installments: Installments;
  address: Address;
  shipping: Shipping;
  seller_address: SellerAddress;
  attributes: Attribute[];
  original_price: null;
  category_id: string;
  official_store_id: null;
  domain_id: string;
  catalog_product_id: null;
  tags: string[];
  order_backend: number;
  use_thumbnail_id: boolean;
  offer_score: null;
  offer_share: null;
  match_score: null;
  winner_item_id: null;
  melicoin: null;
  discounts: null;
}

export interface Address {
  state_id: string;
  state_name: string;
  city_id: string;
  city_name: string;
}

export interface Attribute {
  id: string;
  name: string;
  value_name: string;
  values: AttributeValue[];
  source: number;
  value_id: null | string;
  value_struct: Struct | null;
  attribute_group_id: string;
  attribute_group_name: string;
}

export interface Struct {
  number: number;
  unit: string;
}

export interface AttributeValue {
  id: null | string;
  name: string;
  struct: Struct | null;
  source: number;
}

export interface Installments {
  quantity: number;
  amount: number;
  rate: number;
  currency_id: string;
}

export interface Prices {
  id: string;
  prices: Price[];
  presentation: Presentation;
  payment_method_prices: any[];
  reference_prices: Price[];
  purchase_discounts: any[];
}

export interface Presentation {
  display_currency: string;
}

export interface Price {
  id: string;
  type: string;
  amount: number;
  regular_amount?: null;
  currency_id: string;
  last_updated: string;
  conditions: Conditions;
  exchange_rate_context: string;
  tags?: any[];
}

export interface Conditions {
  context_restrictions: string[];
  start_time: null;
  end_time: null;
  eligible: boolean;
}

export interface Seller {
  id: number;
  permalink: null;
  registration_date: null;
  car_dealer: boolean;
  real_estate_agency: boolean;
  tags: null;
}

export interface SellerAddress {
  id: string;
  comment: string;
  address_line: string;
  zip_code: string;
  country: Sort;
  state: Sort;
  city: Sort;
  latitude: string;
  longitude: string;
}

export interface Shipping {
  free_shipping: boolean;
  mode: string;
  tags: any[];
  logistic_type: string;
  store_pick_up: boolean;
}
